- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present

- name: Install psycopg2
  pip:
    name: psycopg2-binary
    state: present
  become: yes

- name: start and enable postgres daemon
  service:
    name: postgresql
    state: started
    enabled: true
 
- name: Copy pg_hba.conf for local peer authentication method
  copy:
    src: pg_hba.conf
    dest: /etc/postgresql/12/main/pg_hba.conf
    owner: "{{ db_user }}"
    group: "{{ db_user }}"
    mode: "0644"
  become: yes
  
- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted
  become: yes


- name: Setting password to postgres user 
  become: true
  become_user: root
  shell: sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '{{ db_user_password }}';"

- name: Changing type of authentication to password
  become: true
  become_user: root
  shell: sudo sed -i "s/peer/md5/g" /etc/postgresql/12/main/pg_hba.conf

- name: Changing listening interfaces to all
  become: true
  become_user: root
  shell: sudo sed -i "s/#listen_addresses/listen_addresses/g" /etc/postgresql/12/main/postgresql.conf

- name: Changing listening interfaces to all
  become: true
  become_user: root
  shell: sudo sed -i "s/listen_addresses = 'localhost'/listen_addresses = '*'/g" /etc/postgresql/12/main/postgresql.conf


- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted
  become: yes

- name: Create a postgres DB
  community.postgresql.postgresql_db:
    login_user: "{{ db_user }}"
    login_password: "{{ db_user_password }}"
    db: "{{ item }}"
    state: present
  loop: "{{ db_name }}"


