/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "str_to_lower_and_x.check" instead.
 */

#include <check.h>

#line 1 "str_to_lower_and_x.check"
#include <check.h>

#include "../s21_calc.h"

START_TEST(test_str_to_lower_number1)
{
#line 6
char s[] = "XXX";
char result[] = "xxx";
s21_to_lower(s);
ck_assert_str_eq(result, s);

}
END_TEST

START_TEST(test_str_to_lower_number2)
{
#line 12
char s[] = "123";
char result[] = "123";
s21_to_lower(s);
ck_assert_str_eq(result, s);

}
END_TEST

START_TEST(test_str_to_lower_number3)
{
#line 18
char s[] = "";
char result[] = "";
s21_to_lower(s);
ck_assert_str_eq(result, s);

}
END_TEST

START_TEST(test_str_to_lower_number4)
{
#line 24
char s[] = " ";
char result[] = " ";
s21_to_lower(s);
ck_assert_str_eq(result, s);

}
END_TEST

START_TEST(test_str_to_lower_number5)
{
#line 30
char s[] = "xxx";
char result[] = "xxx";
s21_to_lower(s);
ck_assert_str_eq(result, s);

}
END_TEST

START_TEST(test_str_to_lower_number6)
{
#line 36
char s[] = "ok";
char result[] = "ok";
s21_to_lower(NULL);
ck_assert_str_eq(result, s);

}
END_TEST

START_TEST(test_str_to_lower_number7)
{
#line 42
char s[] = "ok";
char result[] = "ok";
s21_replaceX(NULL, "x");
ck_assert_str_eq(result, s);

}
END_TEST

START_TEST(test_str_to_lower_number8)
{
#line 48
char s[1024] = "sin(x)-3.4+6.0+6+6+6+6+6+66+6+6+6+6+6+6++6+6+6+6+6+6+6";
char result[] = "sin((0-0.000000000000000004))-3.4+6.0+6+6+6+6+6+66+6+6+6+6+6+6++6+6+6+6+6+6+6";
s21_replaceX(s, "-0.000000000000000004");
ck_assert_str_eq(result, s);

}
END_TEST

START_TEST(test_str_to_lower_number9)
{
#line 54
char s[1024] = "sin(x)+cos(x)";
char result[1023] = "s(x)+c(x)";
s21_replace_functions(s);
ck_assert_str_eq(result, s);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test_str_to_lower_number1);
    tcase_add_test(tc1_1, test_str_to_lower_number2);
    tcase_add_test(tc1_1, test_str_to_lower_number3);
    tcase_add_test(tc1_1, test_str_to_lower_number4);
    tcase_add_test(tc1_1, test_str_to_lower_number5);
    tcase_add_test(tc1_1, test_str_to_lower_number6);
    tcase_add_test(tc1_1, test_str_to_lower_number7);
    tcase_add_test(tc1_1, test_str_to_lower_number8);
    tcase_add_test(tc1_1, test_str_to_lower_number9);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
