-- Session 1
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;

SELECT CURRENT_TIMESTAMP;

-- Session 2
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;

SELECT CURRENT_TIMESTAMP;

-- Session 1
SHOW TRANSACTION ISOLATION LEVEL;

-- Session 2
SHOW TRANSACTION ISOLATION LEVEL;

-- Session 1
SELECT SUM(rating) FROM pizzeria;

SELECT CURRENT_TIMESTAMP;

-- Session 2
SELECT CURRENT_TIMESTAMP;

UPDATE pizzeria SET rating = 5 WHERE name = 'Pizza Hut';

COMMIT;

-- Session 1
SELECT CURRENT_TIMESTAMP;

SELECT SUM(rating) FROM pizzeria;

COMMIT;

SELECT SUM(rating) FROM pizzeria;

SELECT CURRENT_TIMESTAMP;

-- Session 2
SELECT SUM(rating) FROM pizzeria;

SELECT CURRENT_TIMESTAMP;