version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: harry_team
    container_name: harry_wikimaster
    volumes:
      - .:/app
    environment:
      NEO4J_URI: "bolt://neo4j:7687"
      NEO4J_USER: "neo4j"
      NEO4J_PASSWORD: "assassass"
    depends_on:
      - neo4j
    command: /bin/bash

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/assassass
    volumes:
      - ./neo4j_data:/data

