/*
    1. [ref_faculty]
*/
INSERT INTO ref_faculty(name) VALUES ('ИЦЭиИТ');
INSERT INTO ref_faculty(name) VALUES ('МШБиМЭ');
INSERT INTO ref_faculty(name) VALUES ('Integral');
INSERT INTO ref_faculty(name) VALUES ('ФЭП');
INSERT INTO ref_faculty(name) VALUES ('Капитаны');
INSERT INTO ref_faculty(name) VALUES ('ФГРТСИ');
INSERT INTO ref_faculty(name) VALUES ('ФДО');
INSERT INTO ref_faculty(name) VALUES ('ФМ');
INSERT INTO ref_faculty(name) VALUES ('ФакМ');
INSERT INTO ref_faculty(name) VALUES ('ФЭТТ');
INSERT INTO ref_faculty(name) VALUES ('ФФ');
/*
    2. [ref_degree]
*/
INSERT INTO ref_degree(name) VALUES ('Бакалавриат');
INSERT INTO ref_degree(name) VALUES ('Магистратура');
INSERT INTO ref_degree(name) VALUES ('Бакалавриат(СПО)');
INSERT INTO ref_degree(name) VALUES ('Специалитет');
INSERT INTO ref_degree(name) VALUES ('Аспирантура');
/*
    3. [ref_department]
*/
INSERT INTO ref_department(name) VALUES ('Базовая кафедра компании 1С');
INSERT INTO ref_department(name) VALUES ('Базовая кафедра Торгово-промышленной палаты РФ');
INSERT INTO ref_department(name) VALUES ('Базовая кафедра Федеральной антимонопольной службы России');
INSERT INTO ref_department(name) VALUES ('Базовая кафедра финансового контроля, анализа и аудита Главного контрольного управления города Москвы');
INSERT INTO ref_department(name) VALUES ('Базовая кафедра химии инновационных материалов и технологий');
INSERT INTO ref_department(name) VALUES ('Базовая кафедра цифровой экономики института развития информационного общества');
INSERT INTO ref_department(name) VALUES ('Базовая кафедра цифровых технологий в государственном управлении ФГБУ НИИ Восход');
INSERT INTO ref_department(name) VALUES ('Базовая кафедра экономического анализа и корпоративного управления производством и экспортом высокотехнологичной продукции Государственной корпорации Ростех');
INSERT INTO ref_department(name) VALUES ('Капитаны');
INSERT INTO ref_department(name) VALUES ('Кафедра бухгалтерского учета и налогообложения');
INSERT INTO ref_department(name) VALUES ('Кафедра высшей математики');
INSERT INTO ref_department(name) VALUES ('Кафедра государственного и муниципального управления');
INSERT INTO ref_department(name) VALUES ('Кафедра государственно-правовых и уголовно-правовых дисциплин');
INSERT INTO ref_department(name) VALUES ('Кафедра гражданско-правовых дисциплин');
INSERT INTO ref_department(name) VALUES ('Кафедра индустрии гостеприимства, туризма и спорта');
INSERT INTO ref_department(name) VALUES ('Кафедра иностранных языков №1');
INSERT INTO ref_department(name) VALUES ('Кафедра иностранных языков №2');
INSERT INTO ref_department(name) VALUES ('Кафедра иностранных языков №3');
INSERT INTO ref_department(name) VALUES ('Кафедра информатики');
INSERT INTO ref_department(name) VALUES ('Кафедра истории и философии');
INSERT INTO ref_department(name) VALUES ('Кафедра маркетинга');
INSERT INTO ref_department(name) VALUES ('Кафедра математических методов в экономике');
INSERT INTO ref_department(name) VALUES ('Кафедра международного бизнеса и таможенного дела');
INSERT INTO ref_department(name) VALUES ('Кафедра мировой экономики');
INSERT INTO ref_department(name) VALUES ('Кафедра национальной и региональной экономики');
INSERT INTO ref_department(name) VALUES ('Кафедра организационно-управленческих инноваций');
INSERT INTO ref_department(name) VALUES ('Кафедра политической экономии и истории экономической науки');
INSERT INTO ref_department(name) VALUES ('Кафедра политологии и социологии');
INSERT INTO ref_department(name) VALUES ('Кафедра предпринимательства и логистики');
INSERT INTO ref_department(name) VALUES ('Кафедра прикладной информатики и информационной безопасности');
INSERT INTO ref_department(name) VALUES ('Кафедра психологии');
INSERT INTO ref_department(name) VALUES ('Кафедра рекламы, связей с общественностью и дизайна');
INSERT INTO ref_department(name) VALUES ('Кафедра ресторанного бизнеса');
INSERT INTO ref_department(name) VALUES ('Кафедра русского языка и культуры речи');
INSERT INTO ref_department(name) VALUES ('Кафедра статистики');
INSERT INTO ref_department(name) VALUES ('Кафедра теории менеджмента и бизнес-технологий');
INSERT INTO ref_department(name) VALUES ('Кафедра товароведения и товарной экспертизы');
INSERT INTO ref_department(name) VALUES ('Кафедра торговой политики');
INSERT INTO ref_department(name) VALUES ('Кафедра управления информационными системами и программирования');
INSERT INTO ref_department(name) VALUES ('Кафедра управления проектами и программами');
INSERT INTO ref_department(name) VALUES ('Кафедра физического воспитания');
INSERT INTO ref_department(name) VALUES ('Кафедра финансов и цен');
INSERT INTO ref_department(name) VALUES ('Кафедра финансового менеджмента');
INSERT INTO ref_department(name) VALUES ('Кафедра Финансовые рынки');
INSERT INTO ref_department(name) VALUES ('Кафедра экономики промышленности');
INSERT INTO ref_department(name) VALUES ('Кафедра экономической теории');
/*
    4. [ref_group]
*/
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-01Э/18', 1, 1, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-02ПМ/18', 1, 1, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-03ПМ/18', 1, 1, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-04ПИ/18', 1, 1, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-05ПИ/18', 1, 1, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-06ИБ/18', 1, 1, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-07ИБ/18', 1, 1, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-08БИ/18', 1, 1, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-09БИ/18', 1, 1, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-10МО/18', 1, 1, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-11МО/18', 1, 1, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-12ИБ/18с', 3, 1, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-13ПИ/18с', 3, 1, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-01Э/17', 1, 2, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-02Э/17', 1, 2, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-03ПМ/17', 1, 2, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-04ПИ/17', 1, 2, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-05ПИ/17', 1, 2, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-06ИБ/17', 1, 2, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-07ИБ/17', 1, 2, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-08БИ/17', 1, 2, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-09БИ/17', 1, 2, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-10МО/17', 1, 2, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('291Д-13ПИ/17с', 3, 2, 1);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('01/2018-МИСП', 1, 1, 5);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('02/2018-МИСП', 1, 1, 5);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('03/2018-МИСП', 1, 1, 5);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('04/2018-МИСП', 1, 1, 5);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('05/2018-МИСП', 1, 1, 5);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('06/2018-МИСП', 1, 1, 5);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('07/2018-МИСП', 1, 1, 5);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('01/2016-МО', 1, 3, 5);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('02/2016-ГиМУ', 1, 3, 5);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('11/2018-ИСП', 2, 1, 5);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('17Д-2402ФиК/15', 1, 4, 11);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('17Д-2403ФиК/15', 1, 4, 11);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('17Д-2404КФ/15', 1, 4, 11);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('17Д-2406ЦБ/15', 1, 4, 11);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('17Д-2407БД/15', 1, 4, 11);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('17Д-2414ФМ/15', 1, 4, 11);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('17Д-01ФМ/18', 2, 1, 11);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('17Д-02/18', 2, 1, 11);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('17Д-03/18', 2, 1, 11);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('17Д-04/18', 2, 1, 11);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('17Д-05/18', 2, 1, 11);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('17Д-06/18', 2, 1, 11);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('17Д-07/18', 2, 1, 11);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('17Д-01ФМ/17', 2, 2, 11);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('17Д-02/17', 2, 2, 11);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('17Д-03/17', 2, 2, 11);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('17Д-04/17', 2, 2, 11);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('17Д-05/17', 2, 2, 11);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('17Д-06/17', 2, 2, 11);
INSERT INTO ref_group(group_num, degree_id, course, faculty_id) VALUES ('17Д-07/17', 2, 2, 11);
/*
    5. [student]
*/
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Журавлёв', 'Гордей', 'Лукьянович', '1997-12-24', 58232238, 'ZHuravlyovGoLu@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Козлов', 'Модест', 'Аристархович', '1999-02-23', 67720832, 'KozlovMoAr@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Медведев', 'Аввакум', 'Германович', '1999-10-20', 96760476, 'MedvedevAvGe@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Мухин', 'Эдуард', 'Пантелеймонович', '2000-10-16', 68584684, 'MuhinEHPa@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Егоров', 'Терентий', 'Вячеславович', '2000-09-30', 48465986, 'EgorovTeVy@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Захаров', 'Аркадий', 'Куприянович', '1999-09-01', 74386607, 'ZaharovArKu@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Мамонтов', 'Юрий', 'Святославович', '1997-12-31', 20054293, 'MamontovYUSv@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Козлов', 'Касьян', 'Даниилович', '1997-12-27', 42677943, 'KozlovKaDa@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Мухин', 'Семен', 'Кириллович', '1998-03-07', 29667570, 'MuhinSeKi@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Ершов', 'Абрам', 'Валерьянович', '1997-04-04', 67068893, 'ErshovAbVa@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Устинов', 'Ираклий', 'Германович', '1998-11-10', 70615566, 'UstinovIrGe@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Агафонов', 'Эрик', 'Кимович', '1997-05-24', 88545521, 'AgafonovEHKi@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Сафонов', 'Ярослав', 'Станиславович', '1997-04-02', 52375547, 'SafonovYASt@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Сазонов', 'Максим', 'Тарасович', '2000-08-20', 97370747, 'SazonovMaTa@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Коновалов', 'Никифор', 'Григорьевич', '1997-10-24', 76399912, 'KonovalovNiGr@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Ефимов', 'Соломон', 'Ростиславович', '1999-01-29', 55382533, 'EfimovSoRo@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Морозов', 'Евдоким', 'Антонович', '2000-11-18', 79229275, 'MorozovEvAn@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Степанов', 'Наум', 'Александрович', '1999-04-07', 40664988, 'StepanovNaAl@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Васильев', 'Адольф', 'Юрьевич', '1999-07-06', 77874573, 'VasilevAdYU@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Филатов', 'Тихон', 'Юрьевич', '1999-03-17', 24223888, 'FilatovTiYU@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Анисимов', 'Агафон', 'Федорович', '2000-03-12', 34762383, 'AnisimovAgFe@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Шилов', 'Юлий', 'Егорович', '1999-08-10', 92558246, 'SHilovYUEg@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Капустин', 'Вилен', 'Иосифович', '1998-11-13', 16000317, 'KapustinViIo@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Ефремов', 'Гарри', 'Якунович', '1997-02-03', 40462909, 'EfremovGaYA@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Лазарев', 'Богдан', 'Петрович', '1998-03-23', 83210611, 'LazarevBoPe@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Гаврилов', 'Азарий', 'Ростиславович', '1997-08-02', 86104557, 'GavrilovAzRo@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Прохоров', 'Варлам', 'Святославович', '1997-09-22', 69944805, 'ProhorovVaSv@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Наумов', 'Митрофан', 'Кимович', '1996-09-03', 38670250, 'NaumovMiKi@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Рожков', 'Макар', 'Якунович', '2001-01-05', 29147896, 'RozhkovMaYA@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Кулагин', 'Юрий', 'Парфеньевич', '2000-02-18', 17544012, 'KulaginYUPa@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Мельников', 'Виктор', 'Ростиславович', '1997-05-05', 81877129, 'MelnikovViRo@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Селезнёв', 'Арсений', 'Рудольфович', '1997-11-02', 27097662, 'SeleznyovArRu@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Поляков', 'Людвиг', 'Авдеевич', '1998-01-07', 56580196, 'PolyakovLyAv@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Большаков', 'Виссарион', 'Ростиславович', '1999-07-14', 78804567, 'BolshakovViRo@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Веселов', 'Исаак', 'Лукьянович', '1999-11-27', 21206695, 'VeselovIsLu@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Ефимов', 'Мстислав', 'Вячеславович', '1999-11-03', 25592512, 'EfimovMsVy@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Мамонтов', 'Юстиниан', 'Денисович', '1998-07-28', 16733945, 'MamontovYUDe@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Куликов', 'Рубен', 'Денисович', '1998-08-26', 51281127, 'KulikovRuDe@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Константинов', 'Игнат', 'Богданович', '1996-07-31', 76759386, 'KonstantinovIgBo@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Жданов', 'Нинель', 'Парфеньевич', '1998-10-24', 78150639, 'ZHdanovNiPa@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Жуков', 'Клемент', 'Олегович', '1999-08-03', 60381671, 'ZHukovKlOl@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Титов', 'Прохор', 'Святославович', '1998-01-30', 91849211, 'TitovPrSv@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Уваров', 'Мартын', 'Кимович', '1997-05-22', 49800329, 'UvarovMaKi@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Елисеев', 'Гурий', 'Борисович', '2000-10-19', 57702739, 'EliseevGuBo@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Осипова', 'Романа', 'Натановна', '1996-07-12', 53175815, 'OsipovaRoNa@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Пестова', 'Кира', 'Евсеевна', '1997-09-11', 98172615, 'PestovaKiEv@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Капустина', 'Вилора', 'Вадимовна', '1998-12-12', 52976646, 'KapustinaViVa@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Денисова', 'Даниэла', 'Лаврентьевна', '2000-05-06', 98881921, 'DenisovaDaLa@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Дементьева', 'Зара', 'Федотовна', '1998-06-27', 20161925, 'DementevaZaFe@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Прохорова', 'Инга', 'Натановна', '1996-08-11', 64093194, 'ProhorovaInNa@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Кондратьева', 'Сусанна', 'Адольфовна', '1999-12-18', 75889841, 'KondratevaSuAd@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Шарова', 'Аида', 'Филатовна', '1999-03-29', 70610551, 'SHarovaAiFi@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Алексеева', 'Вероника', 'Юлиановна', '1997-03-08', 53587673, 'AlekseevaVeYU@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Мартынова', 'Валентина', 'Олеговна', '1997-01-12', 46199764, 'MartynovaVaOl@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Овчинникова', 'Милослава', 'Геннадьевна', '1996-12-16', 40604282, 'OvchinnikovaMiGe@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Иванова', 'Гера', 'Серапионовна', '1998-12-22', 64949406, 'IvanovaGeSe@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Шашкова', 'Малика', 'Станиславовна', '1996-11-06', 53353490, 'SHashkovaMaSt@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Родионова', 'Нева', 'Ивановна', '1999-12-27', 32474364, 'RodionovaNeIv@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Бирюкова', 'Адель', 'Тарасовна', '2000-05-03', 52884846, 'BiryukovaAdTa@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Назарова', 'Карина', 'Иосифовна', '2000-11-05', 71711268, 'NazarovaKaIo@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Гущина', 'Анита', 'Авдеевна', '1998-02-27', 86806876, 'GushchinaAnAv@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Макарова', 'Неонила', 'Вячеславовна', '1999-10-10', 43861575, 'MakarovaNeVy@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Зыкова', 'Верона', 'Валерьевна', '1999-01-03', 32043252, 'ZykovaVeVa@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Егорова', 'Элеонора', 'Эдуардовна', '1996-09-22', 41678671, 'EgorovaEHEH@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Лукина', 'Иветта', 'Семёновна', '1996-09-28', 83572984, 'LukinaIvSe@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Блинова', 'Янина', 'Пётровна', '1997-03-04', 73841510, 'BlinovaYAPy@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Терентьева', 'Эльвина', 'Станиславовна', '1996-08-12', 20469820, 'TerentevaEHSt@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Медведева', 'Иоланта', 'Альвиановна', '1999-12-18', 39403758, 'MedvedevaIoAl@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Бурова', 'Тамара', 'Иринеевна', '1996-10-26', 26455959, 'BurovaTaIr@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Зуева', 'Генриетта', 'Гордеевна', '1996-09-01', 83808014, 'ZuevaGeGo@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Давыдова', 'Нора', 'Мартыновна', '1997-02-27', 20899667, 'DavydovaNoMa@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Данилова', 'Марианна', 'Иосифовна', '2000-06-22', 47697226, 'DanilovaMaIo@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Шестакова', 'Нева', 'Ярославовна', '1999-08-16', 72903319, 'SHestakovaNeYA@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Мышкина', 'Янита', 'Всеволодовна', '1997-02-23', 99446789, 'MyshkinaYAVs@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Тетерина', 'Келен', 'Пётровна', '1999-04-13', 27555686, 'TeterinaKePy@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Авдеева', 'Юлиана', 'Протасьевна', '1999-10-07', 33090853, 'AvdeevaYUPr@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Суворова', 'Радослава', 'Тимофеевна', '1998-05-11', 68915007, 'SuvorovaRaTi@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Шестакова', 'Ванда', 'Максимовна', '1998-11-30', 90186606, 'SHestakovaVaMa@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Силина', 'Зара', 'Денисовна', '1997-02-05', 95829177, 'SilinaZaDe@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Тетерина', 'Бронислава', 'Тарасовна', '1998-12-21', 61281658, 'TeterinaBrTa@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Волкова', 'Эмма', 'Петровна', '1999-04-12', 74875782, 'VolkovaEHPe@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Фролова', 'Анжиолетта', 'Дамировна', '1996-11-21', 45635558, 'FrolovaAnDa@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Калашникова', 'Флора', 'Авксентьевна', '1997-08-08', 43704406, 'KalashnikovaFlAv@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Волкова', 'Юстина', 'Евсеевна', '1997-08-15', 74034626, 'VolkovaYUEv@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Дорофеева', 'Ирэна', 'Ярославовна', '1997-08-11', 85083370, 'DorofeevaIrYA@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Хохлова', 'Лия', 'Федоровна', '1998-04-23', 66855607, 'HohlovaLiFe@rea.ru', 0);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Хохлова', 'Зоряна', 'Ивановна', '1999-11-08', 66973695, 'HohlovaZoIv@rea.ru', 1);
INSERT INTO student(surname, name, lastname, birthday, phone, email, is_monitor) VALUES ('Михайлова', 'Сильва', 'Германовна', '2000-07-22', 66777966, 'MihajlovaSiGe@rea.ru', 0);
/*
    6. [student_group]
*/
INSERT INTO student_group(student_id, group_id) VALUES (1, 1);
INSERT INTO student_group(student_id, group_id) VALUES (2, 1);
INSERT INTO student_group(student_id, group_id) VALUES (3, 2);
INSERT INTO student_group(student_id, group_id) VALUES (4, 2);
INSERT INTO student_group(student_id, group_id) VALUES (5, 3);
INSERT INTO student_group(student_id, group_id) VALUES (6, 3);
INSERT INTO student_group(student_id, group_id) VALUES (7, 4);
INSERT INTO student_group(student_id, group_id) VALUES (8, 4);
INSERT INTO student_group(student_id, group_id) VALUES (9, 5);
INSERT INTO student_group(student_id, group_id) VALUES (10, 5);
INSERT INTO student_group(student_id, group_id) VALUES (11, 6);
INSERT INTO student_group(student_id, group_id) VALUES (12, 6);
INSERT INTO student_group(student_id, group_id) VALUES (13, 7);
INSERT INTO student_group(student_id, group_id) VALUES (14, 7);
INSERT INTO student_group(student_id, group_id) VALUES (15, 8);
INSERT INTO student_group(student_id, group_id) VALUES (16, 8);
INSERT INTO student_group(student_id, group_id) VALUES (17, 9);
INSERT INTO student_group(student_id, group_id) VALUES (18, 9);
INSERT INTO student_group(student_id, group_id) VALUES (19, 10);
INSERT INTO student_group(student_id, group_id) VALUES (20, 10);
INSERT INTO student_group(student_id, group_id) VALUES (21, 11);
INSERT INTO student_group(student_id, group_id) VALUES (22, 11);
INSERT INTO student_group(student_id, group_id) VALUES (23, 12);
INSERT INTO student_group(student_id, group_id) VALUES (24, 12);
INSERT INTO student_group(student_id, group_id) VALUES (25, 13);
INSERT INTO student_group(student_id, group_id) VALUES (26, 13);
INSERT INTO student_group(student_id, group_id) VALUES (27, 14);
INSERT INTO student_group(student_id, group_id) VALUES (28, 14);
INSERT INTO student_group(student_id, group_id) VALUES (29, 15);
INSERT INTO student_group(student_id, group_id) VALUES (30, 15);
INSERT INTO student_group(student_id, group_id) VALUES (31, 16);
INSERT INTO student_group(student_id, group_id) VALUES (32, 16);
INSERT INTO student_group(student_id, group_id) VALUES (33, 17);
INSERT INTO student_group(student_id, group_id) VALUES (34, 17);
INSERT INTO student_group(student_id, group_id) VALUES (35, 18);
INSERT INTO student_group(student_id, group_id) VALUES (36, 18);
INSERT INTO student_group(student_id, group_id) VALUES (37, 19);
INSERT INTO student_group(student_id, group_id) VALUES (38, 19);
INSERT INTO student_group(student_id, group_id) VALUES (39, 20);
INSERT INTO student_group(student_id, group_id) VALUES (40, 20);
INSERT INTO student_group(student_id, group_id) VALUES (41, 21);
INSERT INTO student_group(student_id, group_id) VALUES (42, 21);
INSERT INTO student_group(student_id, group_id) VALUES (43, 22);
INSERT INTO student_group(student_id, group_id) VALUES (44, 22);
INSERT INTO student_group(student_id, group_id) VALUES (45, 23);
INSERT INTO student_group(student_id, group_id) VALUES (46, 23);
INSERT INTO student_group(student_id, group_id) VALUES (47, 24);
INSERT INTO student_group(student_id, group_id) VALUES (48, 24);
INSERT INTO student_group(student_id, group_id) VALUES (49, 25);
INSERT INTO student_group(student_id, group_id) VALUES (50, 25);
INSERT INTO student_group(student_id, group_id) VALUES (51, 26);
INSERT INTO student_group(student_id, group_id) VALUES (52, 27);
INSERT INTO student_group(student_id, group_id) VALUES (53, 28);
INSERT INTO student_group(student_id, group_id) VALUES (54, 29);
INSERT INTO student_group(student_id, group_id) VALUES (55, 30);
INSERT INTO student_group(student_id, group_id) VALUES (56, 31);
INSERT INTO student_group(student_id, group_id) VALUES (57, 32);
INSERT INTO student_group(student_id, group_id) VALUES (58, 33);
INSERT INTO student_group(student_id, group_id) VALUES (59, 34);
INSERT INTO student_group(student_id, group_id) VALUES (60, 35);
INSERT INTO student_group(student_id, group_id) VALUES (61, 36);
INSERT INTO student_group(student_id, group_id) VALUES (62, 37);
INSERT INTO student_group(student_id, group_id) VALUES (63, 38);
INSERT INTO student_group(student_id, group_id) VALUES (64, 39);
INSERT INTO student_group(student_id, group_id) VALUES (65, 40);
INSERT INTO student_group(student_id, group_id) VALUES (66, 41);
INSERT INTO student_group(student_id, group_id) VALUES (67, 42);
INSERT INTO student_group(student_id, group_id) VALUES (68, 43);
INSERT INTO student_group(student_id, group_id) VALUES (69, 44);
INSERT INTO student_group(student_id, group_id) VALUES (70, 45);
INSERT INTO student_group(student_id, group_id) VALUES (71, 46);
INSERT INTO student_group(student_id, group_id) VALUES (72, 47);
INSERT INTO student_group(student_id, group_id) VALUES (73, 48);
INSERT INTO student_group(student_id, group_id) VALUES (74, 49);
INSERT INTO student_group(student_id, group_id) VALUES (75, 50);
INSERT INTO student_group(student_id, group_id) VALUES (76, 51);
INSERT INTO student_group(student_id, group_id) VALUES (77, 52);
INSERT INTO student_group(student_id, group_id) VALUES (78, 53);
INSERT INTO student_group(student_id, group_id) VALUES (79, 54);
INSERT INTO student_group(student_id, group_id) VALUES (80, 54);
INSERT INTO student_group(student_id, group_id) VALUES (81, 54);
INSERT INTO student_group(student_id, group_id) VALUES (82, 54);
INSERT INTO student_group(student_id, group_id) VALUES (83, 54);
INSERT INTO student_group(student_id, group_id) VALUES (84, 54);
INSERT INTO student_group(student_id, group_id) VALUES (85, 54);
INSERT INTO student_group(student_id, group_id) VALUES (86, 54);
INSERT INTO student_group(student_id, group_id) VALUES (87, 54);
INSERT INTO student_group(student_id, group_id) VALUES (88, 54);
/*
    7. [ref_subject]
*/
INSERT INTO ref_subject(name) VALUES ('Адаптивные методы прогнозирования');
INSERT INTO ref_subject(name) VALUES ('Администрирование информационных систем');
INSERT INTO ref_subject(name) VALUES ('Алгебра и теория чисел');
INSERT INTO ref_subject(name) VALUES ('Аппаратные средства вычислительной техники');
INSERT INTO ref_subject(name) VALUES ('Архитектура предприятий');
INSERT INTO ref_subject(name) VALUES ('Базы данных и экспертные системы');
INSERT INTO ref_subject(name) VALUES ('Безопасность жизнедеятельности');
INSERT INTO ref_subject(name) VALUES ('Бизнес-статистика');
INSERT INTO ref_subject(name) VALUES ('Бухгалтерский и управленческий учёт');
INSERT INTO ref_subject(name) VALUES ('Введение в профессию');
INSERT INTO ref_subject(name) VALUES ('Вычислительные системы, сети и телекоммуникации');
INSERT INTO ref_subject(name) VALUES ('Геометрия и типология');
INSERT INTO ref_subject(name) VALUES ('Дискретная математика и математическая логика');
INSERT INTO ref_subject(name) VALUES ('Дифференциальные и разностные уравнения');
INSERT INTO ref_subject(name) VALUES ('Документоведение');
INSERT INTO ref_subject(name) VALUES ('Иностранный язык');
INSERT INTO ref_subject(name) VALUES ('Институциональная экономика');
INSERT INTO ref_subject(name) VALUES ('Интернет-программирование');
INSERT INTO ref_subject(name) VALUES ('Информационная безопасность');
INSERT INTO ref_subject(name) VALUES ('Информационно-аналитическое обеспечение безопасности бизнеса');
INSERT INTO ref_subject(name) VALUES ('Информационно-психологическая безопасность');
INSERT INTO ref_subject(name) VALUES ('Информационные системы и технологии');
INSERT INTO ref_subject(name) VALUES ('Информационные системы управление производственной компанией');
INSERT INTO ref_subject(name) VALUES ('Информационные технологии в экономике');
INSERT INTO ref_subject(name) VALUES ('Информационные технологии и системы');
INSERT INTO ref_subject(name) VALUES ('Информационный менеджмент');
INSERT INTO ref_subject(name) VALUES ('Исследование операций и методы оптимизации');
INSERT INTO ref_subject(name) VALUES ('История');
INSERT INTO ref_subject(name) VALUES ('История информатики и развития информационного общества');
INSERT INTO ref_subject(name) VALUES ('История экономических учений');
INSERT INTO ref_subject(name) VALUES ('Комплексный анализ');
INSERT INTO ref_subject(name) VALUES ('Криптографические методы защиты информации');
INSERT INTO ref_subject(name) VALUES ('Культурология');
INSERT INTO ref_subject(name) VALUES ('Линейная алгебра');
INSERT INTO ref_subject(name) VALUES ('Макроэкономика');
INSERT INTO ref_subject(name) VALUES ('Маркетинг');
INSERT INTO ref_subject(name) VALUES ('Математическая логика и теория алгоритмов');
INSERT INTO ref_subject(name) VALUES ('Математические методы финансового анализа');
INSERT INTO ref_subject(name) VALUES ('Математический анализ');
INSERT INTO ref_subject(name) VALUES ('Математическое и имитационное моделирование');
INSERT INTO ref_subject(name) VALUES ('Менеджмент');
INSERT INTO ref_subject(name) VALUES ('Методы оптимизации');
INSERT INTO ref_subject(name) VALUES ('Микроэкономика');
INSERT INTO ref_subject(name) VALUES ('Мировая экономика и международные экономические отношения');
INSERT INTO ref_subject(name) VALUES ('Мировые информационные ресурсы');
INSERT INTO ref_subject(name) VALUES ('Многомерные статистические методы');
INSERT INTO ref_subject(name) VALUES ('Моделирование бизнес-процессов');
INSERT INTO ref_subject(name) VALUES ('Налоги и налогообложение');
INSERT INTO ref_subject(name) VALUES ('Облачные вычисления');
INSERT INTO ref_subject(name) VALUES ('Обработка отраслевой информации');
INSERT INTO ref_subject(name) VALUES ('Объектно-ориентированное программирование');
INSERT INTO ref_subject(name) VALUES ('Объектно-ориентированные технологии в программной инженерии');
INSERT INTO ref_subject(name) VALUES ('Операционные системы');
INSERT INTO ref_subject(name) VALUES ('Организационное и правовое обеспечение информационной безопасности');
INSERT INTO ref_subject(name) VALUES ('Организация безопасности корпоративных сетей');
INSERT INTO ref_subject(name) VALUES ('Основы информационной безопасности');
INSERT INTO ref_subject(name) VALUES ('Основы кибернетики');
INSERT INTO ref_subject(name) VALUES ('Основы права интеллектуальной собственности');
INSERT INTO ref_subject(name) VALUES ('Основы предметно-ориентированного программирования');
INSERT INTO ref_subject(name) VALUES ('Основы технико-экономических систем');
INSERT INTO ref_subject(name) VALUES ('Основы управления информационной безопасностью');
INSERT INTO ref_subject(name) VALUES ('Основы цифровой экономики');
INSERT INTO ref_subject(name) VALUES ('Планирование и прогнозирование в экономике');
INSERT INTO ref_subject(name) VALUES ('Право');
INSERT INTO ref_subject(name) VALUES ('Прикладная математическая статистика');
INSERT INTO ref_subject(name) VALUES ('Прогнозирование социально-демографическиъ структур');
INSERT INTO ref_subject(name) VALUES ('Программирование и администрирование в среде СУБД');
INSERT INTO ref_subject(name) VALUES ('Программная инженерия');
INSERT INTO ref_subject(name) VALUES ('Программно-аппаратные средства защиты информации');
INSERT INTO ref_subject(name) VALUES ('Проектирование интелектуальных информационных систем');
INSERT INTO ref_subject(name) VALUES ('Проектирование информационных систем');
INSERT INTO ref_subject(name) VALUES ('Проектирование корпоративных информационных систем');
INSERT INTO ref_subject(name) VALUES ('Проектирование программной архитектуры');
INSERT INTO ref_subject(name) VALUES ('Проектирование систем управления взаимоотношениями с клиентами');
INSERT INTO ref_subject(name) VALUES ('Психология');
INSERT INTO ref_subject(name) VALUES ('Разработка информационных систем');
INSERT INTO ref_subject(name) VALUES ('Разработка мобильных приложений');
INSERT INTO ref_subject(name) VALUES ('Разработка распределённых приложений');
INSERT INTO ref_subject(name) VALUES ('Распределённые системы');
INSERT INTO ref_subject(name) VALUES ('Региональная экономика');
INSERT INTO ref_subject(name) VALUES ('Реинжиниринг и управление бизнес-процессами');
INSERT INTO ref_subject(name) VALUES ('Рынки ИКТ и организация продаж');
INSERT INTO ref_subject(name) VALUES ('Системное программирование');
INSERT INTO ref_subject(name) VALUES ('Социальная статистика');
INSERT INTO ref_subject(name) VALUES ('Социально-экономическая статистика');
INSERT INTO ref_subject(name) VALUES ('Социология');
INSERT INTO ref_subject(name) VALUES ('Стандарты информационной безопасности');
INSERT INTO ref_subject(name) VALUES ('Статистика');
INSERT INTO ref_subject(name) VALUES ('Статистика финансов');
INSERT INTO ref_subject(name) VALUES ('Структура данных и алгоритмы');
INSERT INTO ref_subject(name) VALUES ('Структуры и алгоритмы компьютерной обработки данных');
INSERT INTO ref_subject(name) VALUES ('Схемотехнические основы средств вычислительной техники');
INSERT INTO ref_subject(name) VALUES ('Теоретические основы информатики');
INSERT INTO ref_subject(name) VALUES ('Теоретические основы компьютерной безопасности');
INSERT INTO ref_subject(name) VALUES ('Теория вероятностей и математическая статистика');
INSERT INTO ref_subject(name) VALUES ('Теория выборочных обследований');
INSERT INTO ref_subject(name) VALUES ('Теория вычислительных процессов и структур');
INSERT INTO ref_subject(name) VALUES ('Теория графов и сетей');
INSERT INTO ref_subject(name) VALUES ('Теория игр');
INSERT INTO ref_subject(name) VALUES ('Теория информации');
INSERT INTO ref_subject(name) VALUES ('Теория оптимального управления');
INSERT INTO ref_subject(name) VALUES ('Теория принятия решений');
INSERT INTO ref_subject(name) VALUES ('Теория риска');
INSERT INTO ref_subject(name) VALUES ('Теория систем и системный анализ');
INSERT INTO ref_subject(name) VALUES ('Теория статистики');
INSERT INTO ref_subject(name) VALUES ('Техническая защита информации');
INSERT INTO ref_subject(name) VALUES ('Технологии разработки программного обеспечения');
INSERT INTO ref_subject(name) VALUES ('Технологии разработки современных программных комплексов');
INSERT INTO ref_subject(name) VALUES ('Управление IT-сервисами и контентом');
INSERT INTO ref_subject(name) VALUES ('Управление жизненным циклом информационных систем');
INSERT INTO ref_subject(name) VALUES ('Управление электронным бизнесом');
INSERT INTO ref_subject(name) VALUES ('Физика');
INSERT INTO ref_subject(name) VALUES ('Философия');
INSERT INTO ref_subject(name) VALUES ('Финансовая математика');
INSERT INTO ref_subject(name) VALUES ('Финансы');
INSERT INTO ref_subject(name) VALUES ('Функциональный анализ');
INSERT INTO ref_subject(name) VALUES ('Численные методы');
INSERT INTO ref_subject(name) VALUES ('Эконометрика и Эконометрическое моделирование');
INSERT INTO ref_subject(name) VALUES ('Экономика труда');
INSERT INTO ref_subject(name) VALUES ('Экономика фирмы');
INSERT INTO ref_subject(name) VALUES ('Экономическая статистика');
INSERT INTO ref_subject(name) VALUES ('Экономическая теория');
INSERT INTO ref_subject(name) VALUES ('Экономическая теория, менеджмент, маркетинг, бухгалтерский учёт');
INSERT INTO ref_subject(name) VALUES ('Экономический анализ');
INSERT INTO ref_subject(name) VALUES ('Электротехнические основы средств вычислительной техники');
INSERT INTO ref_subject(name) VALUES ('Этика делового общения');
INSERT INTO ref_subject(name) VALUES ('Языки и методы программирования');
/*
    8. [employee]
*/
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Нямина', 'Валерия', 'Елисеевна', 33, '1966-05-30', 90573285, 'NyaminaVaEl@rea.ru', 40);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Шерстова', 'Софья', 'Ростиславовна', 20, '1974-06-07', 47859259, 'SHerstovaSoRo@rea.ru', 10);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Миронова', 'Варвара', 'Петровна', 42, '1975-02-07', 92911666, 'MironovaVaPe@rea.ru', 9);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Путилин', 'Владилен', 'Леонтиевич', 17, '1976-11-19', 15177861, 'PutilinVlLe@rea.ru', 18);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Антоновича', 'Ксения', 'Анатолиевна', 41, '1981-02-24', 97795192, 'AntonovichaKsAn@rea.ru', 41);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Дубровин', 'Измаил', 'Анатолиевич', 42, '1979-12-16', 91260365, 'DubrovinIzAn@rea.ru', 4);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Абумайлова', 'Фаина', 'Игнатиевна', 32, '1964-12-03', 73773596, 'AbumajlovaFaIg@rea.ru', 11);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Якшина', 'Анфиса', 'Николаевна', 36, '1971-12-17', 33319578, 'YAkshinaAnNi@rea.ru', 8);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Державин', 'Руслан', 'Севастьянович', 40, '1974-06-25', 85271138, 'DerzhavinRuSe@rea.ru', 25);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Кулигин', 'Рюрик', 'Иннокентиевич', 28, '1978-07-19', 55293128, 'KuliginRyIn@rea.ru', 23);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Кузаева', 'Римма', 'Трофимовна', 40, '1964-03-22', 45325655, 'KuzaevaRiTr@rea.ru', 24);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Задкова', 'Дина', 'Афанасиевна', 15, '1965-07-26', 43397474, 'ZadkovaDiAf@rea.ru', 8);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Попова', 'Евгения', 'Иосифовна', 29, '1974-02-03', 26144390, 'PopovaEvIo@rea.ru', 24);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Бобров', 'Аркадий', 'Адрианович', 20, '1978-06-13', 79961737, 'BobrovArAd@rea.ru', 23);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Губанова', 'Бронислава', 'Николаевна', 35, '1964-04-19', 58743822, 'GubanovaBrNi@rea.ru', 21);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Якубенко', 'Порфирий', 'Кондратович', 31, '1967-05-06', 92526346, 'YAkubenkoPoKo@rea.ru', 16);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Тычкина', 'Кристина', 'Виталиевна', 50, '1975-12-23', 48924450, 'TychkinaKrVi@rea.ru', 14);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Кругликова', 'Евдокия', 'Тимуровна', 13, '1979-07-08', 42546045, 'KruglikovaEvTi@rea.ru', 20);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Левкин', 'Всеслав', 'Ульянович', 3, '1968-12-31', 34620410, 'LevkinVsUl@rea.ru', 29);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Радыгина', 'Любовь', 'Андрияновна', 11, '1967-04-20', 69348513, 'RadyginaLyAn@rea.ru', 27);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Малышева', 'Майя', 'Степановна', 49, '1977-01-16', 20474927, 'MalyshevaMaSt@rea.ru', 41);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Тенишев', 'Николай', 'Савелиевич', 2, '1975-02-22', 55543259, 'TenishevNiSa@rea.ru', 22);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Кетов', 'Марк', 'Захарович', 6, '1968-07-13', 43143847, 'KetovMaZa@rea.ru', 17);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Загидуллина', 'Владислава', 'Юлиевна', 45, '1972-11-20', 76994001, 'ZagidullinaVlYU@rea.ru', 11);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Воликов', 'Никита', 'Ираклиевич', 33, '1973-08-19', 61134011, 'VolikovNiIr@rea.ru', 19);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Нустрова', 'Мария', 'Яновна', 34, '1965-06-24', 12394242, 'NustrovaMaYA@rea.ru', 24);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Ячменькова', 'Ираида', 'Никитевна', 33, '1966-12-15', 46414681, 'YAchmenkovaIrNi@rea.ru', 17);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Кириченко', 'Зиновий', 'Никанорович', 23, '1978-09-03', 18070640, 'KirichenkoZiNi@rea.ru', 28);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Апакидзе', 'Харитон', 'Герасимович', 15, '1970-05-13', 38598492, 'ApakidzeHaGe@rea.ru', 7);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Кумовьева', 'Ольга', 'Станиславовна', 19, '1969-09-02', 67387918, 'KumovevaOlSt@rea.ru', 4);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Кулика', 'Эмилия', 'Алексеевна', 6, '1971-04-19', 83679994, 'KulikaEHAl@rea.ru', 3);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Сутулин', 'Харитон', 'Прохорович', 1, '1969-03-13', 16625326, 'SutulinHaPr@rea.ru', 21);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Филиппов', 'Зиновий', 'Касьянович', 6, '1964-02-04', 26189784, 'FilippovZiKa@rea.ru', 36);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Каменева', 'Алиса', 'Данилевна', 47, '1968-02-26', 80340654, 'KamenevaAlDa@rea.ru', 8);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Дуркина', 'Ариадна', 'Афанасиевна', 3, '1967-09-08', 67919930, 'DurkinaArAf@rea.ru', 14);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Елагина', 'Мария', 'Андрияновна', 47, '1978-09-25', 92196574, 'ElaginaMaAn@rea.ru', 46);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Силина', 'Марианна', 'Брониславовна', 32, '1979-06-23', 47787100, 'SilinaMaBr@rea.ru', 21);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Родиков', 'Павел', 'Брониславович', 43, '1961-02-25', 26540457, 'RodikovPaBr@rea.ru', 20);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Кубланова', 'Наталия', 'Елисеевна', 39, '1964-05-18', 13238078, 'KublanovaNaEl@rea.ru', 45);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Лаптева', 'Лидия', 'Иларионовна', 50, '1972-11-11', 87668079, 'LaptevaLiIl@rea.ru', 27);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Васнев', 'Эдуард', 'Модестович', 25, '1966-03-19', 16390271, 'VasnevEHMo@rea.ru', 16);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Пирожкова', 'Каролина', 'Степановна', 9, '1975-06-15', 61687200, 'PirozhkovaKaSt@rea.ru', 2);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Шаляпин', 'Иннокентий', 'Игоревич', 39, '1967-05-02', 87221410, 'SHalyapinInIg@rea.ru', 10);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Качаева', 'Любава', 'Николаевна', 21, '1975-03-24', 14269456, 'KachaevaLyNi@rea.ru', 19);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Островерха', 'Елизавета', 'Давидовна', 29, '1963-02-10', 97088493, 'OstroverhaElDa@rea.ru', 14);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Петрищева', 'Диана', 'Борисовна', 10, '1965-04-29', 30980197, 'PetrishchevaDiBo@rea.ru', 2);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Дарюшин', 'Артемий', 'Изяславович', 14, '1980-08-22', 10645615, 'DaryushinArIz@rea.ru', 26);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Флёрова', 'Римма', 'Данииловна', 22, '1964-01-09', 87090096, 'FlyorovaRiDa@rea.ru', 32);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Ионов', 'Аскольд', 'Ираклиевич', 25, '1963-01-03', 10770410, 'IonovAsIr@rea.ru', 21);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Сергеевича', 'Лариса', 'Всеволодовна', 23, '1976-10-31', 16438531, 'SergeevichaLaVs@rea.ru', 10);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Язынина', 'Таисия', 'Николаевна', 37, '1965-09-22', 74883194, 'YAzyninaTaNi@rea.ru', 39);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Андреева', 'Ольга', 'Алексеевна', 25, '1962-09-18', 89779332, 'AndreevaOlAl@rea.ru', 19);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Карасевич', 'Изяслав', 'Мечиславович', 9, '1970-04-23', 13273153, 'KarasevichIzMe@rea.ru', 46);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Бузинский', 'Викентий', 'Арсениевич', 46, '1972-03-01', 52929563, 'BuzinskijViAr@rea.ru', 30);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Тимирёва', 'Инна', 'Ефимовна', 36, '1963-05-14', 69790113, 'TimiryovaInEf@rea.ru', 40);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Кваскова', 'Милена', 'Федотовна', 43, '1973-12-04', 31736292, 'KvaskovaMiFe@rea.ru', 3);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Митрохина', 'Ольга', 'Фомевна', 11, '1965-02-21', 60919573, 'MitrohinaOlFo@rea.ru', 23);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Нуряев', 'Константин', 'Брониславович', 30, '1966-12-12', 65862291, 'NuryaevKoBr@rea.ru', 16);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Шабалина', 'Злата', 'Анатолиевна', 25, '1980-01-01', 12567310, 'SHabalinaZlAn@rea.ru', 39);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Серёгин', 'Архип', 'Святославович', 26, '1971-01-16', 58822448, 'SeryoginArSv@rea.ru', 38);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Казаков', 'Ростислав', 'Серафимович', 49, '1977-03-12', 50200074, 'KazakovRoSe@rea.ru', 1);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Бебнев', 'Анатолий', 'Андронович', 4, '1975-10-12', 95345468, 'BebnevAnAn@rea.ru', 39);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Бок', 'Фадей', 'Евлампиевич', 5, '1972-12-17', 33356832, 'BokFaEv@rea.ru', 2);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Фуриков', 'Герман', 'Валериевич', 11, '1962-11-30', 56920959, 'FurikovGeVa@rea.ru', 46);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Квартин', 'Казимир', 'Мирославович', 16, '1976-12-25', 67555052, 'KvartinKaMi@rea.ru', 20);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Апраксин', 'Казимир', 'Ипполитович', 24, '1979-09-07', 64235184, 'ApraksinKaIp@rea.ru', 31);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Элефтерова', 'Ефросиния', 'Мироновна', 8, '1970-03-10', 58945695, 'EHlefterovaEfMi@rea.ru', 16);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Мичуев', 'Михаил', 'Иванович', 15, '1972-12-13', 32623433, 'MichuevMiIv@rea.ru', 19);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Осолодкина', 'Алина', 'Степановна', 28, '1962-04-04', 94273663, 'OsolodkinaAlSt@rea.ru', 37);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Копорикова', 'Лариса', 'Евгениевна', 35, '1973-07-11', 95709227, 'KoporikovaLaEv@rea.ru', 4);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Нугаева', 'Татьяна', 'Юлиевна', 34, '1962-07-16', 89117280, 'NugaevaTaYU@rea.ru', 14);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Шелепин', 'Мирослав', 'Назарович', 16, '1979-06-07', 31843796, 'SHelepinMiNa@rea.ru', 7);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Шаршина', 'Роза', 'Николаевна', 9, '1972-02-06', 18210290, 'SHarshinaRoNi@rea.ru', 15);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Козлитина', 'Дина', 'Давидовна', 35, '1964-10-06', 10931994, 'KozlitinaDiDa@rea.ru', 46);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Грекова', 'Софья', 'Владленовна', 7, '1968-01-04', 71064043, 'GrekovaSoVl@rea.ru', 40);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Щеткин', 'Мстислав', 'Аникитевич', 44, '1976-04-22', 56593602, 'SHCHetkinMsAn@rea.ru', 15);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Нарыков', 'Кир', 'Самсонович', 21, '1975-06-04', 46827568, 'NarykovKiSa@rea.ru', 10);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Дмитриева', 'Анфиса', 'Ираклиевна', 21, '1961-07-10', 64008107, 'DmitrievaAnIr@rea.ru', 26);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Арзамасцева', 'Полина', 'Станиславовна', 20, '1965-01-28', 11699061, 'ArzamascevaPoSt@rea.ru', 7);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Садовский', 'Вячеслав', 'Дмитриевич', 1, '1968-07-06', 87262590, 'SadovskijVyDm@rea.ru', 8);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Кахадзе', 'Вера', 'Иосифовна', 35, '1961-05-07', 93194562, 'KahadzeVeIo@rea.ru', 30);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Сай', 'Бронислав', 'Андреевич', 7, '1965-12-31', 54308424, 'SajBrAn@rea.ru', 11);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Юрков', 'Иван', 'Маркович', 39, '1967-07-14', 76171783, 'YUrkovIvMa@rea.ru', 27);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Мандрыка', 'Марианна', 'Геннадиевна', 18, '1965-11-17', 20475265, 'MandrykaMaGe@rea.ru', 15);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Потапова', 'Дина', 'Ипполитовна', 37, '1965-03-17', 24307003, 'PotapovaDiIp@rea.ru', 24);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Матизов', 'Данила', 'Михеевич', 15, '1981-10-22', 55481191, 'MatizovDaMi@rea.ru', 25);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Ростов', 'Владилен', 'Эрнестович', 39, '1967-01-03', 11399438, 'RostovVlEH@rea.ru', 1);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Казнова', 'Елена', 'Александровна', 19, '1976-05-11', 36586991, 'KaznovaElAl@rea.ru', 32);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Игнаткович', 'Адам', 'Несторович', 21, '1971-10-24', 50639100, 'IgnatkovichAdNe@rea.ru', 27);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Молчанова', 'Зоя', 'Яновна', 47, '1981-09-07', 68668639, 'MolchanovaZoYA@rea.ru', 46);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Витаев', 'Тимофей', 'Изяславович', 40, '1972-09-08', 93277079, 'VitaevTiIz@rea.ru', 38);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Филиппова', 'Раиса', 'Игнатиевна', 9, '1974-10-22', 36536288, 'FilippovaRaIg@rea.ru', 37);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Акулиничев', 'Алексей', 'Онисимович', 1, '1967-10-01', 75965242, 'AkulinichevAlOn@rea.ru', 21);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Козарис', 'Кузьма', 'Мартьянович', 41, '1977-07-24', 15501416, 'KozarisKuMa@rea.ru', 9);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Пустов', 'Зиновий', 'Мартьянович', 10, '1967-04-11', 45714109, 'PustovZiMa@rea.ru', 1);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Янсон', 'Мирон', 'Никанорович', 29, '1962-01-10', 73126391, 'YAnsonMiNi@rea.ru', 22);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Чиграков', 'Евсей', 'Григориевич', 16, '1964-11-03', 12514367, 'CHigrakovEvGr@rea.ru', 10);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Ахременко', 'Никита', 'Егорович', 11, '1980-12-24', 62259367, 'AhremenkoNiEg@rea.ru', 19);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Кулумбаева', 'Марианна', 'Ивановна', 37, '1970-10-02', 63255043, 'KulumbaevaMaIv@rea.ru', 20);
INSERT INTO employee(surname, name, lastname, stazh, birthday, phone, email, ref_department_id) VALUES ('Щепетинникова', 'Вероника', 'Иосифовна', 7, '1975-04-13', 16995046, 'SHCHepetinnikovaVeIo@rea.ru', 32);
/*
    9. [mark_rating_sheet]
*/
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (82, 126, 1, 1, 1, 80, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (85, 11, 1, 0, 1, 60, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (48, 63, 2, 0, 1, 40, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (70, 60, 2, 1, 0, 60, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (4, 74, 3, 0, 1, 80, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (100, 46, 3, 1, 0, 60, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (36, 66, 4, 1, 0, 40, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (65, 103, 4, 0, 1, 60, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (7, 110, 5, 1, 1, 80, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (9, 11, 5, 1, 1, 60, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (12, 3, 6, 1, 1, 40, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (71, 79, 6, 0, 1, 60, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (22, 21, 7, 1, 1, 80, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (37, 126, 7, 1, 0, 60, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (61, 118, 8, 0, 1, 40, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (13, 7, 8, 1, 0, 60, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (19, 123, 9, 1, 0, 80, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (26, 60, 9, 1, 0, 60, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (68, 127, 10, 0, 1, 40, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (40, 56, 10, 1, 1, 60, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (66, 81, 11, 0, 1, 80, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (12, 84, 11, 1, 0, 60, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (10, 28, 12, 1, 0, 40, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (84, 49, 12, 1, 0, 60, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (39, 1, 13, 1, 0, 80, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (47, 107, 13, 0, 1, 60, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (40, 120, 14, 1, 1, 40, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (74, 43, 14, 1, 0, 60, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (27, 62, 15, 1, 0, 80, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (44, 39, 15, 0, 1, 60, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (83, 92, 16, 1, 1, 40, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (88, 59, 16, 1, 0, 60, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (85, 61, 17, 1, 0, 80, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (44, 99, 17, 0, 1, 60, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (75, 69, 18, 0, 1, 40, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (50, 13, 18, 0, 1, 60, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (19, 91, 19, 1, 1, 80, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (25, 99, 19, 1, 0, 60, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (81, 43, 20, 1, 1, 40, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (27, 95, 20, 1, 1, 60, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (32, 125, 21, 0, 1, 80, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (63, 91, 21, 1, 0, 60, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (92, 19, 22, 1, 0, 40, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (28, 38, 22, 1, 1, 60, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (40, 15, 23, 1, 1, 80, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (27, 41, 23, 0, 1, 60, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (66, 90, 24, 1, 0, 40, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (31, 3, 24, 1, 1, 60, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (98, 3, 25, 1, 0, 80, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (42, 44, 25, 0, 1, 60, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (12, 79, 26, 1, 0, 40, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (69, 70, 26, 1, 1, 60, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (79, 24, 27, 1, 0, 80, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (65, 54, 27, 1, 1, 60, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (22, 108, 28, 0, 1, 40, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (94, 51, 28, 1, 1, 60, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (19, 11, 29, 1, 0, 80, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (79, 121, 29, 0, 1, 60, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (30, 122, 30, 1, 0, 40, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (5, 93, 30, 1, 0, 60, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (98, 104, 31, 0, 1, 80, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (24, 13, 31, 0, 1, 60, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (22, 93, 32, 1, 0, 40, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (10, 87, 32, 0, 1, 60, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (84, 23, 33, 1, 1, 80, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (85, 75, 33, 1, 0, 60, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (58, 25, 34, 0, 1, 40, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (96, 107, 34, 0, 1, 60, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (12, 55, 35, 1, 0, 80, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (100, 90, 35, 1, 1, 60, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (100, 105, 36, 1, 1, 40, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (10, 64, 36, 1, 0, 60, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (49, 84, 37, 0, 1, 80, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (91, 13, 37, 0, 1, 60, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (9, 43, 38, 1, 0, 40, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (47, 10, 38, 0, 1, 60, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (59, 99, 39, 1, 1, 80, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (66, 71, 39, 1, 0, 60, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (91, 5, 40, 1, 0, 40, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (78, 109, 40, 0, 1, 60, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (92, 51, 41, 1, 1, 80, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (99, 84, 41, 0, 1, 60, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (38, 65, 42, 1, 0, 40, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (17, 96, 42, 0, 1, 60, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (21, 115, 43, 1, 1, 80, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (64, 14, 43, 1, 0, 60, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (70, 15, 44, 1, 1, 40, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (4, 19, 44, 0, 1, 60, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (52, 62, 45, 1, 0, 80, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (43, 82, 45, 1, 1, 60, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (89, 16, 46, 1, 1, 40, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (80, 112, 46, 1, 0, 60, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (10, 46, 47, 0, 1, 80, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (42, 124, 47, 1, 1, 60, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (21, 21, 48, 1, 0, 40, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (69, 46, 48, 0, 1, 60, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (74, 100, 49, 1, 1, 80, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (39, 34, 49, 0, 1, 60, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (27, 51, 50, 0, 1, 40, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (87, 40, 50, 1, 0, 60, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (83, 11, 51, 1, 1, 80, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (65, 100, 51, 0, 1, 60, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (32, 30, 52, 1, 1, 40, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (36, 105, 52, 0, 1, 60, 8);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (84, 119, 53, 1, 0, 80, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (9, 81, 53, 0, 1, 60, 2);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (38, 71, 54, 1, 0, 40, 4);
INSERT INTO mark_rating_sheet(employee_id, subject_id, group_id, is_lecturer, is_tutor, working_hours, duration) VALUES (4, 70, 54, 1, 1, 60, 8);
/*
    10. [daily_mark_raiting_record]
*/
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (1, 1, '2018-12-09', 0, 1, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (1, 2, '2018-12-09', 0, 0, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (2, 1, '2018-12-09', 1, 0, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (2, 2, '2018-12-09', 0, 2, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (3, 3, '2018-12-09', 0, 5, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (3, 4, '2018-12-09', 0, 0, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (4, 3, '2018-12-09', 0, 0, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (4, 4, '2018-12-09', 0, 1, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (5, 5, '2018-12-09', 0, 4, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (5, 6, '2018-12-09', 1, 5, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (6, 5, '2018-12-09', 0, 1, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (6, 6, '2018-12-09', 0, 5, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (7, 7, '2018-12-09', 0, 1, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (7, 8, '2018-12-09', 1, 3, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (8, 7, '2018-12-09', 0, 5, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (8, 8, '2018-12-09', 1, 2, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (9, 9, '2018-12-09', 0, 4, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (9, 10, '2018-12-09', 1, 4, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (10, 9, '2018-12-09', 1, 0, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (10, 10, '2018-12-09', 1, 2, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (11, 11, '2018-12-09', 0, 5, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (11, 12, '2018-12-09', 1, 1, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (12, 11, '2018-12-09', 1, 2, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (12, 12, '2018-12-09', 1, 1, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (13, 13, '2018-12-09', 0, 1, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (13, 14, '2018-12-09', 1, 5, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (14, 13, '2018-12-09', 1, 2, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (14, 14, '2018-12-09', 1, 1, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (15, 15, '2018-12-09', 1, 2, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (15, 16, '2018-12-09', 0, 2, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (16, 15, '2018-12-09', 1, 4, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (16, 16, '2018-12-09', 1, 3, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (17, 17, '2018-12-09', 1, 4, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (17, 18, '2018-12-09', 0, 2, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (18, 17, '2018-12-09', 1, 3, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (18, 18, '2018-12-09', 1, 0, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (19, 19, '2018-12-09', 1, 1, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (19, 20, '2018-12-09', 0, 4, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (20, 19, '2018-12-09', 1, 2, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (20, 20, '2018-12-09', 1, 0, 0, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (1, 1, '2018-12-16', 0, 4, 5, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (1, 2, '2018-12-16', 1, 0, 9, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (2, 1, '2018-12-16', 1, 1, 7, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (2, 2, '2018-12-16', 0, 1, 6, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (3, 3, '2018-12-16', 1, 1, 2, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (3, 4, '2018-12-16', 1, 3, 2, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (4, 3, '2018-12-16', 0, 5, 4, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (4, 4, '2018-12-16', 1, 3, 2, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (5, 5, '2018-12-16', 1, 0, 4, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (5, 6, '2018-12-16', 1, 2, 9, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (6, 5, '2018-12-16', 1, 1, 8, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (6, 6, '2018-12-16', 1, 0, 10, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (7, 7, '2018-12-16', 0, 3, 3, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (7, 8, '2018-12-16', 1, 3, 7, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (8, 7, '2018-12-16', 1, 3, 9, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (8, 8, '2018-12-16', 0, 5, 3, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (9, 9, '2018-12-16', 0, 5, 7, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (9, 10, '2018-12-16', 1, 2, 8, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (10, 9, '2018-12-16', 1, 3, 7, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (10, 10, '2018-12-16', 0, 2, 2, 0);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (21, 21, '2018-12-10', 1, 0, 0, 20);
INSERT INTO daily_mark_rating_record(mark_rating_sheet_id, student_id, date, attendance, activity, tests, exam) VALUES (21, 22, '2018-12-10', 1, 0, 0, 40);
