-- Session 1
BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;

SELECT CURRENT_TIMESTAMP;

-- Session 2
BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;

SELECT CURRENT_TIMESTAMP;

-- Session 1
SHOW TRANSACTION ISOLATION LEVEL;

-- Session 2
SHOW TRANSACTION ISOLATION LEVEL;

-- Session 1
SELECT SUM(rating) FROM pizzeria;

SELECT CURRENT_TIMESTAMP;

-- Session 2
UPDATE pizzeria SET rating = 1.0 WHERE name = 'Pizza Hut';

SELECT CURRENT_TIMESTAMP;

COMMIT;

-- Session 1
SELECT SUM(rating) FROM pizzeria;

SELECT CURRENT_TIMESTAMP;

COMMIT;

SELECT SUM(rating) FROM pizzeria;

SELECT CURRENT_TIMESTAMP;

-- Session 2
SELECT SUM(rating) FROM pizzeria;

SELECT CURRENT_TIMESTAMP;