-- Session 1
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;

SELECT CURRENT_TIMESTAMP;

-- Session 2
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;

SELECT CURRENT_TIMESTAMP;

-- Session 1
SHOW TRANSACTION ISOLATION LEVEL;

-- Session 2
SHOW TRANSACTION ISOLATION LEVEL;

-- Session 1
SELECT CURRENT_TIMESTAMP;

UPDATE pizzeria SET rating = 1.5 WHERE id = 1;

-- Session 2
SELECT CURRENT_TIMESTAMP;

UPDATE pizzeria SET rating = 3.5 WHERE id = 2;

-- Session 1
SELECT CURRENT_TIMESTAMP;

UPDATE pizzeria SET rating = 4.5 WHERE id = 2;

-- Session 2
SELECT CURRENT_TIMESTAMP;

UPDATE pizzeria SET rating = 1.2 WHERE id = 1;

-- Session 1
SELECT CURRENT_TIMESTAMP;

COMMIT;

-- Session 2
SELECT CURRENT_TIMESTAMP;

COMMIT;

-- Session 1
SELECT * FROM pizzeria;

-- Session 2
SELECT * FROM pizzeria;