---
- name: Install JDK + maven
  apt:
    name: 
      - openjdk-8-jdk
      - maven
    state: present

- name: Copy Java source code hotel-service
  copy:
    src: hotel-service/
    dest: hotel-service/
    owner: vagrant
    group: vagrant

- name: Build
  shell: |
    if [ ! -f /home/vagrant/hotel-service/target/app.jar ]; then
      cd /home/vagrant/hotel-service && mvn -B package -DskipTests -DfinalName=app &&
      mv /home/vagrant/hotel-service/target/*.jar /home/vagrant/hotel-service/target/app.jar;
    fi

- name: Deploy systemd unit for hotels-service
  template:
    src: "hotels-service.service.j2"
    dest: "/etc/systemd/system/hotels-service.service"
    owner: consul
    group: consul
    mode: "0644"


- name: Start hotel service
  service:
    daemon_reload: true
    name: hotels-service
    state: started
    enabled: yes
