-- Session 1
SELECT CURRENT_TIMESTAMP;

BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;

-- Session 2
SELECT CURRENT_TIMESTAMP;

BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;

-- Session 1
SHOW TRANSACTION ISOLATION LEVEL;

-- Session 2
SHOW TRANSACTION ISOLATION LEVEL;

--Session 1
SELECT CURRENT_TIMESTAMP;

SELECT rating FROM pizzeria WHERE name = 'Pizza Hut';

--Session 2
SELECT CURRENT_TIMESTAMP;

UPDATE pizzeria SET rating = 3.6 WHERE name = 'Pizza Hut';

COMMIT;

--Session 1
SELECT CURRENT_TIMESTAMP;

SELECT rating FROM pizzeria WHERE name = 'Pizza Hut';

COMMIT;

SELECT CURRENT_TIMESTAMP;

SELECT rating FROM pizzeria WHERE name = 'Pizza Hut';

--Session 2
SELECT CURRENT_TIMESTAMP;

SELECT rating FROM pizzeria WHERE name = 'Pizza Hut';