/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "str_validation.check" instead.
 */

#include <check.h>

#line 1 "str_validation.check"
#include <check.h>

#include "../s21_calc.h"

START_TEST(test_str_validation_number1)
{
#line 6
char symbol = 'i';
int code = s21_is_characters(symbol);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number2)
{
#line 11
char symbol = ')';
int code = s21_is_characters(symbol);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number3)
{
#line 16
char symbol = '+';
int code = s21_is_characters(symbol);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number4)
{
#line 21
char symbol = '-';
int code = s21_is_characters(symbol);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number5)
{
#line 26
char symbol = '*';
int code = s21_is_characters(symbol);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number6)
{
#line 31
char symbol = '/';
int code = s21_is_characters(symbol);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number7)
{
#line 36
char symbol = '^';
int code = s21_is_characters(symbol);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number8)
{
#line 41
char symbol = 'm';
int code = s21_is_characters(symbol);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number9)
{
#line 46
char symbol = 'o';
int code = s21_is_characters(symbol);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number10)
{
#line 51
char symbol = 'd';
int code = s21_is_characters(symbol);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number11)
{
#line 56
char symbol = 'c';
int code = s21_is_characters(symbol);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number12)
{
#line 61
char symbol = 's';
int code = s21_is_characters(symbol);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number13)
{
#line 66
char symbol = 'i';
int code = s21_is_characters(symbol);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number14)
{
#line 71
char symbol = 'n';
int code = s21_is_characters(symbol);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number15)
{
#line 76
char symbol = 't';
int code = s21_is_characters(symbol);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number16)
{
#line 81
char symbol = 'a';
int code = s21_is_characters(symbol);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number17)
{
#line 86
char symbol = 'q';
int code = s21_is_characters(symbol);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number18)
{
#line 91
char symbol = 'r';
int code = s21_is_characters(symbol);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number19)
{
#line 96
char symbol = 'l';
int code = s21_is_characters(symbol);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number20)
{
#line 101
char symbol = 'g';
int code = s21_is_characters(symbol);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number21)
{
#line 106
char symbol = 'x';
int code = s21_is_characters(symbol);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number22)
{
#line 111
char symbol = '.';
int code = s21_is_characters(symbol);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number23)
{
#line 116
char symbol = ',';
int code = s21_is_characters(symbol);
ck_assert_int_eq(1, code);

}
END_TEST

START_TEST(test_str_validation_number24)
{
#line 121
char symbol = 'w';
int code = s21_is_characters(symbol);
ck_assert_int_eq(1, code);

}
END_TEST

START_TEST(test_str_validation_number25)
{
#line 126
char symbol = '<';
int code = s21_is_characters(symbol);
ck_assert_int_eq(1, code);

}
END_TEST

START_TEST(test_str_validation_number26)
{
#line 131
char symbol = 'z';
int code = s21_is_characters(symbol);
ck_assert_int_eq(1, code);

}
END_TEST

START_TEST(test_str_validation_number27)
{
#line 136
char s[] = "sin(x)-2";
int code = s21_valid_characters(s);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number28)
{
#line 141
char s[] = "sin(x)-2.9";
int code = s21_valid_characters(s);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number29)
{
#line 146
char s[] = "sin(x)-2,9";
int code = s21_valid_characters(s);
ck_assert_int_eq(1, code);

}
END_TEST

START_TEST(test_str_validation_number30)
{
#line 151
int code = s21_valid_characters(NULL);
ck_assert_int_eq(2, code);

}
END_TEST

START_TEST(test_str_validation_number31)
{
#line 155
char s[] = "sin(x)-2,9";
int code = s21_is_str_empty(s);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number32)
{
#line 160
char s[] = "";
int code = s21_is_str_empty(s);
ck_assert_int_eq(3, code);

}
END_TEST

START_TEST(test_str_validation_number33)
{
#line 165
char s[] = "Errors not found\n\nPlease, enter 'AC'";
ck_assert_str_eq(s21_strerror(0), s);

}
END_TEST

START_TEST(test_str_validation_number34)
{
#line 169
char s[] = "sin(x)-2,9";
int code = s21_expression_size(s);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number35)
{
#line 174
char s[] = "s";
int code = s21_expression_size(s);
ck_assert_int_eq(4, code);

}
END_TEST

START_TEST(test_str_validation_number36)
{
#line 179
char s[] = "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq";
int code = s21_expression_size(s);
ck_assert_int_eq(5, code);

}
END_TEST

START_TEST(test_str_validation_number37)
{
#line 184
char s[] = "()";
int code = s21_brackets_count(s);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number38)
{
#line 189
char s[] = "(())";
int code = s21_brackets_count(s);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number39)
{
#line 194
char s[] = "(()";
int code = s21_brackets_count(s);
ck_assert_int_eq(6, code);

}
END_TEST

START_TEST(test_str_validation_number40)
{
#line 199
char s[] = "sin(x)-2.9";
int code = s21_check_point(s);
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number41)
{
#line 204
char s[] = ".sin(x)-2.9";
int code = s21_check_point(s);
ck_assert_int_eq(ERROR_BAD_EXPRESSION, code);

}
END_TEST

START_TEST(test_str_validation_number42)
{
#line 209
char s[] = "sin(x)-2.9.";
int code = s21_check_point(s);
ck_assert_int_eq(ERROR_BAD_EXPRESSION, code);

}
END_TEST

START_TEST(test_str_validation_number43)
{
#line 214
char s[] = "sin(x)-2..9";
int code = s21_check_point(s);
ck_assert_int_eq(ERROR_BAD_EXPRESSION, code);

}
END_TEST

START_TEST(test_str_validation_number44)
{
#line 219
char s[] = "sin(x)-2.9";
int code = s21_check_operators(s);
ck_assert_int_eq(ERROR_NO, code);

}
END_TEST

START_TEST(test_str_validation_number45)
{
#line 224
char s[] = "1.0-2.9";
int code = s21_check_operators(s);
ck_assert_int_eq(ERROR_NO, code);

}
END_TEST

START_TEST(test_str_validation_number46)
{
#line 229
char s[] = "1.0";
int code = s21_check_operators(s);
ck_assert_int_eq(ERROR_NO_OPERATORS, code);

}
END_TEST

START_TEST(test_str_validation_number47)
{
#line 234
int code = s21_is_operator('+');
ck_assert_int_eq(1, code);

}
END_TEST

START_TEST(test_str_validation_number48)
{
#line 238
int code = s21_is_operator('a');
ck_assert_int_eq(0, code);

}
END_TEST

START_TEST(test_str_validation_number49)
{
#line 242
char s[] = "1.0-2.9";
int code = s21_correct_operators(s);
ck_assert_int_eq(ERROR_NO, code);

}
END_TEST

START_TEST(test_str_validation_number50)
{
#line 247
char s[] = "1.0-2.9-";
int code = s21_correct_operators(s);
ck_assert_int_eq(ERROR_BAD_EXPRESSION, code);

}
END_TEST

START_TEST(test_str_validation_number51)
{
#line 252
char s[] = "1.0-+2.9";
int code = s21_correct_operators(s);
ck_assert_int_eq(ERROR_BAD_EXPRESSION, code);

}
END_TEST

START_TEST(test_str_validation_number52)
{
#line 257
char s[255] = "sin(x)-1.0-+2.9";
int code = s21_check_brackets(s);
ck_assert_int_eq(ERROR_NO, code);

}
END_TEST

START_TEST(test_str_validation_number53)
{
#line 262
char s[255] = "sin)x()+2*3)";
int code = s21_check_brackets(s);
ck_assert_int_eq(ERROR_BAD_BRACKETS, code);

}
END_TEST

START_TEST(test_str_validation_number54)
{
#line 267
char s[255] = "sin(x)-1.0+2.9";
int code = s21_correct_func(s);
ck_assert_int_eq(ERROR_NO, code);

}
END_TEST

START_TEST(test_str_validation_number55)
{
#line 272
char s[255] = "sin4-1.0+2.9";
int code = s21_correct_func(s);
ck_assert_int_eq(ERROR_BAD_EXPRESSION, code);

}
END_TEST

START_TEST(test_str_validation_number56)
{
#line 277
char s[255] = "cos4-1.0+2.9";
int code = s21_correct_func(s);
ck_assert_int_eq(ERROR_BAD_EXPRESSION, code);

}
END_TEST

START_TEST(test_str_validation_number57)
{
#line 282
char s[255] = "tan4-1.0+2.9";
int code = s21_correct_func(s);
ck_assert_int_eq(ERROR_BAD_EXPRESSION, code);

}
END_TEST

START_TEST(test_str_validation_number58)
{
#line 287
char s[255] = "sqrt4-1.0+2.9";
int code = s21_correct_func(s);
ck_assert_int_eq(ERROR_BAD_EXPRESSION, code);

}
END_TEST

START_TEST(test_str_validation_number59)
{
#line 292
char s[255] = "log4-1.0+2.9";
int code = s21_correct_func(s);
ck_assert_int_eq(ERROR_BAD_EXPRESSION, code);

}
END_TEST

START_TEST(test_str_validation_number60)
{
#line 297
char s[255] = "ln4-1.0+2.9";
int code = s21_correct_func(s);
ck_assert_int_eq(ERROR_BAD_EXPRESSION, code);

}
END_TEST

START_TEST(test_str_validation_number61)
{
#line 302
char s[255] = "ln4-1.0+2.9";
int code = s21_last_symbol(s);
ck_assert_int_eq(ERROR_NO, code);

}
END_TEST

START_TEST(test_str_validation_number62)
{
#line 307
char s[255] = "ln4-1.0+(2mod2)";
int code = s21_last_symbol(s);
ck_assert_int_eq(ERROR_NO, code);

}
END_TEST

START_TEST(test_str_validation_number63)
{
#line 312
char s[255] = "ln4-1.0+sin";
int code = s21_last_symbol(s);
ck_assert_int_eq(ERROR_BAD_EXPRESSION, code);

}
END_TEST

START_TEST(test_str_validation_number64)
{
#line 317
char s[255] = "sin(x)";
int code = s21_expression_check(s);
ck_assert_int_eq(ERROR_NO, code);

}
END_TEST

START_TEST(test_str_validation_number65)
{
#line 322
char s[] = "";
int code = s21_expression_check(s);
ck_assert_int_eq(ERROR_EMPTY_STR, code);

}
END_TEST

START_TEST(test_str_validation_number66)
{
#line 327
char s[] = "s";
int code = s21_expression_check(s);
ck_assert_int_eq(ERROR_SHORT_STR, code);

}
END_TEST

START_TEST(test_str_validation_number67)
{
#line 332
char s[] = "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq";
int code = s21_expression_check(s);
ck_assert_int_eq(ERROR_LONG_STR, code);

}
END_TEST

START_TEST(test_str_validation_number68)
{
#line 337
char s[] = "sin(x)-2,9";
int code = s21_expression_check(s);
ck_assert_int_eq(ERROR_BAD_SYMBOL, code);

}
END_TEST

START_TEST(test_str_validation_number69)
{
#line 342
char s[] = "(()";
int code = s21_expression_check(s);
ck_assert_int_eq(ERROR_BAD_BRACKETS, code);

}
END_TEST

START_TEST(test_str_validation_number70)
{
#line 347
char s[] = ".sin(x)-2.9";
int code = s21_expression_check(s);
ck_assert_int_eq(ERROR_BAD_EXPRESSION, code);

}
END_TEST

START_TEST(test_str_validation_number71)
{
#line 352
char s[] = "1.0";
int code = s21_expression_check(s);
ck_assert_int_eq(ERROR_NO_OPERATORS, code);

}
END_TEST

START_TEST(test_str_validation_number72)
{
#line 357
char s[] = "1.0-2.9-";
int code = s21_expression_check(s);
ck_assert_int_eq(ERROR_BAD_EXPRESSION, code);

}
END_TEST

START_TEST(test_str_validation_number73)
{
#line 362
char s[255] = "sin(x))-(1.0-+2.9";
int code = s21_expression_check(s);
ck_assert_int_eq(ERROR_BAD_EXPRESSION, code);

}
END_TEST

START_TEST(test_str_validation_number74)
{
#line 367
char s[255] = "sin4-1.0+2.9";
int code = s21_expression_check(s);
ck_assert_int_eq(ERROR_BAD_EXPRESSION, code);

}
END_TEST

START_TEST(test_str_validation_number75)
{
#line 372
char s[255] = "ln4-1.0+sin";
int code = s21_expression_check(s);
ck_assert_int_eq(ERROR_BAD_EXPRESSION, code);

}
END_TEST

START_TEST(test_str_validation_number76)
{
#line 377
char s[255] = "ln(4)-1.0mod";
int code = s21_expression_check(s);
ck_assert_int_eq(ERROR_BAD_EXPRESSION, code);

}
END_TEST

START_TEST(test_str_validation_number77)
{
#line 382
char s[255] = "sin(x))-(1.0+2.9";
int code = s21_expression_check(s);
ck_assert_int_eq(ERROR_BAD_BRACKETS, code);

}
END_TEST

START_TEST(test_str_validation_number78)
{
#line 387
char s[255] = "s(4.0)+c(4.0)";
char result[255] = "s ( 4.0 )  + c ( 4.0 ) ";
s21_add_separator(s);
ck_assert_str_eq(result, s);

}
END_TEST

START_TEST(test_str_validation_number79)
{
#line 393
char s[255] = "s(4.0)+c(4.0)";
char strarray[500][256];
int code = s21_lexems(s, strarray);
ck_assert_int_eq(1, code);

}
END_TEST

START_TEST(test_str_validation_number80)
{
#line 399
char s[255] = "sin()";
int code = s21_empty_brackets(s);
ck_assert_int_eq(ERROR_EMPTY_BRACKETS, code);

}
END_TEST

START_TEST(test_str_validation_number81)
{
#line 404
char s[255] = "*4";
int code = s21_expression_check(s);
ck_assert_int_eq(ERROR_BAD_EXPRESSION, code);

}
END_TEST

START_TEST(test_str_validation_number82)
{
#line 409
char s[255] = "-4";
int code = s21_expression_check(s);
ck_assert_int_eq(ERROR_NO, code);

}
END_TEST

START_TEST(test_str_validation_number83)
{
#line 414
char s[255] = "sin()";
int code = s21_expression_check(s);
ck_assert_int_eq(ERROR_EMPTY_BRACKETS, code);

}
END_TEST

START_TEST(test_str_validation_number84)
{
#line 419
char s[255] = "-1-(-2)";
int code = s21_first_operator_and_sign(s);
ck_assert_int_eq(ERROR_NO, code);

}
END_TEST

START_TEST(test_str_validation_number85)
{
#line 424
char s[] = "-1*sin(cos(tan(-x^2)^3)^4)";
int code = s21_correct_operators(s);
ck_assert_int_eq(ERROR_NO, code);

}
END_TEST

START_TEST(test_str_validation_number86)
{
#line 429
char s[255] = "-1*sin(cos(tan(-x^2)^3)^4)";
int code = s21_correct_func(s);
ck_assert_int_eq(ERROR_NO, code);

}
END_TEST

START_TEST(test_str_validation_number87)
{
#line 434
char s[255] = "3mod-6";
int code = s21_sing_before_func(s);
ck_assert_int_eq(ERROR_BAD_EXPRESSION, code);

}
END_TEST

START_TEST(test_str_validation_number88)
{
#line 439
char s[] = "3mod-6";
int code = s21_expression_check(s);
ck_assert_int_eq(ERROR_BAD_EXPRESSION, code);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test_str_validation_number1);
    tcase_add_test(tc1_1, test_str_validation_number2);
    tcase_add_test(tc1_1, test_str_validation_number3);
    tcase_add_test(tc1_1, test_str_validation_number4);
    tcase_add_test(tc1_1, test_str_validation_number5);
    tcase_add_test(tc1_1, test_str_validation_number6);
    tcase_add_test(tc1_1, test_str_validation_number7);
    tcase_add_test(tc1_1, test_str_validation_number8);
    tcase_add_test(tc1_1, test_str_validation_number9);
    tcase_add_test(tc1_1, test_str_validation_number10);
    tcase_add_test(tc1_1, test_str_validation_number11);
    tcase_add_test(tc1_1, test_str_validation_number12);
    tcase_add_test(tc1_1, test_str_validation_number13);
    tcase_add_test(tc1_1, test_str_validation_number14);
    tcase_add_test(tc1_1, test_str_validation_number15);
    tcase_add_test(tc1_1, test_str_validation_number16);
    tcase_add_test(tc1_1, test_str_validation_number17);
    tcase_add_test(tc1_1, test_str_validation_number18);
    tcase_add_test(tc1_1, test_str_validation_number19);
    tcase_add_test(tc1_1, test_str_validation_number20);
    tcase_add_test(tc1_1, test_str_validation_number21);
    tcase_add_test(tc1_1, test_str_validation_number22);
    tcase_add_test(tc1_1, test_str_validation_number23);
    tcase_add_test(tc1_1, test_str_validation_number24);
    tcase_add_test(tc1_1, test_str_validation_number25);
    tcase_add_test(tc1_1, test_str_validation_number26);
    tcase_add_test(tc1_1, test_str_validation_number27);
    tcase_add_test(tc1_1, test_str_validation_number28);
    tcase_add_test(tc1_1, test_str_validation_number29);
    tcase_add_test(tc1_1, test_str_validation_number30);
    tcase_add_test(tc1_1, test_str_validation_number31);
    tcase_add_test(tc1_1, test_str_validation_number32);
    tcase_add_test(tc1_1, test_str_validation_number33);
    tcase_add_test(tc1_1, test_str_validation_number34);
    tcase_add_test(tc1_1, test_str_validation_number35);
    tcase_add_test(tc1_1, test_str_validation_number36);
    tcase_add_test(tc1_1, test_str_validation_number37);
    tcase_add_test(tc1_1, test_str_validation_number38);
    tcase_add_test(tc1_1, test_str_validation_number39);
    tcase_add_test(tc1_1, test_str_validation_number40);
    tcase_add_test(tc1_1, test_str_validation_number41);
    tcase_add_test(tc1_1, test_str_validation_number42);
    tcase_add_test(tc1_1, test_str_validation_number43);
    tcase_add_test(tc1_1, test_str_validation_number44);
    tcase_add_test(tc1_1, test_str_validation_number45);
    tcase_add_test(tc1_1, test_str_validation_number46);
    tcase_add_test(tc1_1, test_str_validation_number47);
    tcase_add_test(tc1_1, test_str_validation_number48);
    tcase_add_test(tc1_1, test_str_validation_number49);
    tcase_add_test(tc1_1, test_str_validation_number50);
    tcase_add_test(tc1_1, test_str_validation_number51);
    tcase_add_test(tc1_1, test_str_validation_number52);
    tcase_add_test(tc1_1, test_str_validation_number53);
    tcase_add_test(tc1_1, test_str_validation_number54);
    tcase_add_test(tc1_1, test_str_validation_number55);
    tcase_add_test(tc1_1, test_str_validation_number56);
    tcase_add_test(tc1_1, test_str_validation_number57);
    tcase_add_test(tc1_1, test_str_validation_number58);
    tcase_add_test(tc1_1, test_str_validation_number59);
    tcase_add_test(tc1_1, test_str_validation_number60);
    tcase_add_test(tc1_1, test_str_validation_number61);
    tcase_add_test(tc1_1, test_str_validation_number62);
    tcase_add_test(tc1_1, test_str_validation_number63);
    tcase_add_test(tc1_1, test_str_validation_number64);
    tcase_add_test(tc1_1, test_str_validation_number65);
    tcase_add_test(tc1_1, test_str_validation_number66);
    tcase_add_test(tc1_1, test_str_validation_number67);
    tcase_add_test(tc1_1, test_str_validation_number68);
    tcase_add_test(tc1_1, test_str_validation_number69);
    tcase_add_test(tc1_1, test_str_validation_number70);
    tcase_add_test(tc1_1, test_str_validation_number71);
    tcase_add_test(tc1_1, test_str_validation_number72);
    tcase_add_test(tc1_1, test_str_validation_number73);
    tcase_add_test(tc1_1, test_str_validation_number74);
    tcase_add_test(tc1_1, test_str_validation_number75);
    tcase_add_test(tc1_1, test_str_validation_number76);
    tcase_add_test(tc1_1, test_str_validation_number77);
    tcase_add_test(tc1_1, test_str_validation_number78);
    tcase_add_test(tc1_1, test_str_validation_number79);
    tcase_add_test(tc1_1, test_str_validation_number80);
    tcase_add_test(tc1_1, test_str_validation_number81);
    tcase_add_test(tc1_1, test_str_validation_number82);
    tcase_add_test(tc1_1, test_str_validation_number83);
    tcase_add_test(tc1_1, test_str_validation_number84);
    tcase_add_test(tc1_1, test_str_validation_number85);
    tcase_add_test(tc1_1, test_str_validation_number86);
    tcase_add_test(tc1_1, test_str_validation_number87);
    tcase_add_test(tc1_1, test_str_validation_number88);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
